apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: netcore-dockerize-api
      version: v1
  template:
    metadata:
      labels:
        app: netcore-dockerize-api
        version: v1
    spec:
      containers:
      - name: api-container
        image: acanotech/dockerize-api:2.0
        imagePullPolicy: Always        
        startupProbe:
          httpGet:
            path: /health
            port: 80
          failureThreshold: 30
          periodSeconds: 15
        readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
            successThreshold: 5
        livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
        ports:
        - containerPort: 80        
---

apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: netcore-dockerize-api
  type: LoadBalancer
  ports:
    - name: api-port
      port: 8080
      targetPort: 80